### ISSUE TITLE
KeyError: 'enable'

### ISSUE THREAD

**Issue by willwade** [acidcoke/Grimassist#6]
I have a windows 10 machine which is pretty locked down. I have to install as admin - im wondering if this is just a me error - because on a regular windows machine Im not seeing this. I dare say this is something to do with the paths that ive just tried to fix.. ill try and figure this out later

```
Traceback (most recent call last):
  File "grimassist.py", line 57, in <module>
  File "src\task_killer.py", line 35, in start
  File "src\controllers\mouse_controller.py", line 52, in start
KeyError: 'enable'

```

**Comment by willwade** [comment]
I think from your commit history you’ve tried to fix this. Let me know if it’s outstanding and if it isn’t have you got a list of priorities to work on that if I get a chance I’ll help out on. Great work.

**Comment by acidcoke** [comment]
Let's hope it it's fixed.

I have some stuff planned for the ui so I will create some issues soon. My main priority is support for Linux and Mac.

**Comment by willwade** [comment]
Great. There must be something I'm missing that PyDirectInput is being used for - but I can't see what it is. Your doing fab work :)

**Comment by acidcoke** [comment]
Thank you, I'm giving my best.
